### ISSUE TITLE
Must use import to load ES Module

### ISSUE THREAD

**Issue by lensbart** [formatjs/formatjs-old#200]
Since upgrading `@formatjs/intl-relativetimeformat` from 2.6.3 to 4.1.0, our test suite fails, but only on GitHub Actions:

```
$ jest
5666
internal/modules/cjs/loader.js:958
5667
      throw new ERR_REQUIRE_ESM(filename);
5668
      ^
5669

5670
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/runner/work/codebase/codebase/node_modules/intl-locales-supported/dist/index.js
5671
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:958:13)
5672
    at Module.load (internal/modules/cjs/loader.js:798:32)
5673
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
5674
    at Module.require (internal/modules/cjs/loader.js:838:19)
5675
    at require (internal/modules/cjs/helpers.js:74:18)
5676
    at Object.<anonymous> (/home/runner/work/codebase/codebase/node_modules/react-intl/dist/components/provider.js:35:32)
5677
    at Module._compile (internal/modules/cjs/loader.js:945:30)
5678
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
5679
    at Module.load (internal/modules/cjs/loader.js:798:32)
5680
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
5681
error Command failed with exit code 1.
5682
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I can’t reproduce the issue on my local machine (macOS), but it is reproducible on GitHub Actions (Linux).

Any pointers as to how I could fix or debug this would be greatly appreciated!

**Comment by longlho** [comment]
can you make sure u're on latest greatest of stuff?

**Comment by lensbart** [comment]
Thanks for the quick reply! I’m on 4.1.1 now but still running into the same issue

**Comment by longlho** [comment]
how about `intl-locales-supported` & `react-intl`?

**Comment by lensbart** [comment]
For `react-intl`, I’m on 3.3.1. `intl-locales-supported` isn’t a direct dependency of our project, but it does appear as version 1.5.0 in `node_modules` as a subdependency of `react-intl`. (All our dependencies are up-to-date, by the way!)

**Comment by lensbart** [comment]
Also, should this be relevant, we have the following rule in our Webpack config:
```js
{
  include: [
    path.resolve(__dirname, '../../node_modules/react-intl'),
    path.resolve(__dirname, '../../node_modules/intl-messageformat'),
    path.resolve(__dirname, '../../node_modules/intl-messageformat-parser')
  ],
  test: /\.(js|jsx)$/,
  use: { loader: 'babel-loader' }
}
```

**Comment by longlho** [comment]
what about your `jest` config? Looks like that's the step that's failing?

We use GitHub Actions ourselves and have not seen this issue.

**Comment by lensbart** [comment]
Here it is in all its glory:
```js
// jest.config.js

module.exports = {
  moduleDirectories: ['node_modules'],
  moduleFileExtensions: ['js', 'json', 'jsx'], // 'json' fixes https://github.com/GoogleChrome/puppeteer/issues/2754#issuecomment-403321142
  moduleNameMapper: {
    '\\.(aac|eot|gif|jpeg|jpg|mp3|mp4|m4a|oga|otf|png|svg|ttf|wav|webm|webp|woff|woff2)$':
      '<rootDir>/config/jest/fileMock.js',
    '\\.(css|scss)$': 'identity-obj-proxy'
  },
  preset: 'jest-puppeteer',
  setupFiles: ['<rootDir>/config/jest/setupFile.js'],
  setupFilesAfterEnv: ['<rootDir>/config/jest/setupFileAfterEnv.js'],
  snapshotSerializers: ['enzyme-to-json/serializer'],
  testEnvironment: 'jsdom', // overrides jest-puppeteer preset — make sure to again override this (default) preset at the top of every puppeteer test file
  testPathIgnorePatterns: ['/bin/', '/node_modules/'], // don’t test `bin/test.js`
  testURL: 'http://lvh.me/',
  transform: {
    '^.+\\.graphql$': '<rootDir>/config/jest/graphqlTransformer.js',
    '^.+\\.jsx?$': 'babel-jest'
  },
  transformIgnorePatterns: [
    /** @see https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#jest */
    '/node_modules/(?!intl-messageformat|intl-messageformat-parser).+\\.js$'
  ],
  verbose: true
}
```

**Comment by longlho** [comment]
ok since you're using `babel-jest` I assume you also have a `babel.config.js` file? (Strongly recommend against `.babelrc` because it has weird inheritance issue)

**Comment by lensbart** [comment]
```js
// .babelrc.js
module.exports = {
  env: {
    // these options will be merged on top of the root options
    production: {
      plugins: [
        [
          '@babel/plugin-transform-react-constant-elements',
          { allowMutablePropsOnTags: ['FormattedMessage'] }
        ]
        // 'transform-remove-console'
      ]
    },
    test: {
      plugins: ['dynamic-import-node', 'ramda'],
      // Remove `presets: [...]` once we migrate away from Sequelize
      presets: [
        [
          '@babel/preset-env',
          {
            corejs: 3,
            targets: { node: 'current' }, // fixes https://github.com/sequelize/sequelize/issues/7840#issuecomment-315576088
            useBuiltIns: 'usage'
          }
        ]
      ]
    }
  },
  plugins: [
    ['@babel/plugin-transform-runtime', { corejs: 3 }],
    '@babel/plugin-transform-async-to-generator',
    '@babel/plugin-syntax-dynamic-import',
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-export-default-from',
    ['@babel/plugin-proposal-pipeline-operator', { proposal: 'minimal' }],
    '@babel/plugin-proposal-throw-expressions',
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-proposal-optional-chaining'
    ],
    /** @todo consider using https://github.com/GertjanReynaert/react-intl-translations-manager too */
    ['react-intl', { messagesDir: './build/babel-plugin-react-intl/' }],
    'wildcard'
  ],
  presets: [
    ['@babel/preset-env', { corejs: 3, useBuiltIns: 'usage' }],
    '@babel/preset-flow',
    '@babel/preset-react'
  ]
}
```

**Comment by longlho** [comment]
what Node version do you use and do you run it w/ any special flags?

**Comment by lensbart** [comment]
Local development environment: `v12.8.0`
GitHub Actions: `node-version: 12.x`

Thanks for your help!

**Comment by longlho** [comment]
Nothing seems glaringly wrong here so if you can put together a repro of your setup that'd be great.

**Comment by kikoanis** [comment]
@lensbart This may be related to the node version you are using. I had to downgrade node version for exactly the same issue you have for it to disappear. Hope this helps.

**Comment by srosset81** [comment]
Downgrading node from v12.11.0 to v10.16.3 fixed it for me as well ! Thanks @kikoanis

**Comment by JulienPradet** [comment]
Indeed, I've just ran into the same error here. This happens when I'm running my SSR code. But I would expect the same for anything that's not bundled (tests included).
Here is a reproduction repo : https://github.com/JulienPradet/react-intl-bug

The issue only occurs in node 12.11.0. It works fine in 12.10.0.

**Comment by longlho** [comment]
kk I found the issue, will release a fix soon. Looks like 12.11 turns on ESM by default
